---
- name: Install system dependencies
  ansible.builtin.dnf:
    name:
      - curl
      - wget
      - dnf-plugins-core
    state: present

- name: Run Vector official setup script
  ansible.builtin.shell:
    cmd: |
      bash -c "$(curl -fsSL https://setup.vector.dev)"
    creates: /etc/yum.repos.d/vector.repo

- name: Install Vector package
  ansible.builtin.dnf:
    name: vector
    state: present
    update_cache: true

- name: Create Vector config directory
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: '0755'

- name: Create Vector config
  ansible.builtin.template:
    src: vector.toml.j2
    dest: "{{ vector_config_dir }}/{{ vector_config_file }}"
    mode: '0644'
  notify: restart vector

- name: Start Vector service
  ansible.builtin.systemd:
    name: vector
    state: started
    enabled: true
